# Dependencies
markdown: kramdown
plugins: 
  - jekyll-gist
  - jekyll-feed

# Permalinks
permalink: :title

# Setup
title: unixslayer
tagline: ''
description: ''
url: https://unixslayer.github.io
baseurl: ''

author:
  name: 'unixslayer'
  url: https://twitter.com/kicek_

repository: unixslayer/unixslayer.github.io

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"