# Dependencies
markdown: kramdown
plugins: 
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed

# Permalinks
permalink: :title

# Setup
title: unixslayer
tagline: ''
description: ''
url: https://unixslayer.github.io
baseurl: '/'

author:
  name: 'unixslayer'
  url: https://twitter.com/kicek_

paginate: 5

repository: unixslayer/unixslayer.github.io
